name: freebank
description: Freebank App
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^13.0.0
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_native_splash: ^2.2.17
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  go_router: ^6.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  mockito: ^5.3.2
  open_filex: ^4.3.2
  otp_text_field: ^1.1.3
  retrofit: ^3.3.1
  sentry_dio: ^6.18.2
  sentry_flutter: ^6.18.2
  sentry_logging: ^6.18.2
  splashscreen: ^1.3.5
  camera:
  path_provider:
  path:

dev_dependencies:
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/shara_white_logo.png
    - assets/images/happy-customer.png
    - assets/images/happy-customer-bg.png
  fonts:
    - family: Hellix
      fonts:
        - asset: assets/fonts/Hellix-Regular.ttf
        - asset: assets/fonts/Hellix-Light.ttf
        - asset: assets/fonts/Hellix-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hellix-Black.ttf
          weight: 900
